var countries = [
    "China",
    "United States",
    "United Kingdom",
    "France",
    "Germany",
    "Japan",
    "Australia",
    "Canada",
    "Brazil",
    "India",
    "Russia",
    "South Africa",
    "Mexico",
    "Italy",
    "South Korea",
    "New Zealand",
    "Argentina",
    "Egypt",
    "Switzerland",
    "Netherlands",
    "Sweden",
    "Belgium",
    "Norway",
    "Austria",
    "Denmark",
    "Ireland",
    "Finland",
    "Greece",
    "Portugal",
    "Thailand",
    "Poland",
    "Czech Republic",
    "Turkey",
    "Israel",
    "Saudi Arabia",
    "Malaysia",
    "Singapore",
    "Indonesia",
    "Pakistan",
    "Philippines",
    "Vietnam",
    "Iran",
    "Chile",
    "Nigeria",
    "Panama",
    "Peru",
    "Colombia",
    "Venezuela",
    "United Arab Emirates",
    "Morocco",
    "Hungary",
    "Romania",
    "Kenya",
    "Tanzania",
    "Uganda",
    "Ghana",
    "Chad",
    "Ukraine",
    "Belarus",
    "Kazakhstan",
    "Uzbekistan",
    "Turkmenistan",
    "Kyrgyzstan",
    "Tajikistan",
    "Azerbaijan",
    "Armenia",
    "Georgia",
    "Moldova",
    "Serbia",
    "Montenegro",
    "North Macedonia",
    "Bosnia and Herzegovina",
    "Albania",
    "Kosovo",
    "Croatia",
    "Slovenia",
    "Lithuania",
    "Latvia",
    "Estonia",
    "Iceland",
    "Luxembourg",
    "Cyprus",
    "Malta",
    "Andorra",
    "Monaco",
    "San Marino",
    "Vatican City",
    "Bahamas",
    "Barbados",
    "Jamaica",
    "Trinidad and Tobago",
    "Dominica",
    "Antigua and Barbuda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Grenada",
];